-- PAGINACION EN SQL 
-- LIMIT LIMITA EL TAMAÑO DE LOS REGISTROS
-- OFFSET SITUA EL CURSOR EN EL NUMERO DE REGISTRO INDICADO

--EN POSTGRE
select * from parroquia
ORDER BY PARROQUIA_ID
LIMIT 5 OFFSET (5 * 2-1)

--EN SLQ SERVER

SELECT Top 5*
FROM PARROQUIA
WHERE PARROQUIA_ID NOT IN
(SELECT TOP (5 * 5-1)PARROQUIA_ID 
             FROM PARROQUIA
             ORDER BY PARROQUIA_ID ASC
)
ORDER BY PARROQUIA_ID ASC
           