--ejercicio 1


select * from sector
select * from parroquia WHERE MUNICIPIO_ID = 15 ORDER BY PARROQUIA_ID
select * from municipio where nombre_municipio like '%CABIMAS%'
select * from estado



Select tabla.nombre_municipio,count(nombre_sector)
FROM SECTOR S , 
(SELECT M.NOMBRE_MUNICIPIO, P.NOMBRE_PARROQUIA,P.PARROQUIA_ID,count (P.PARROQUIA_ID) 
FROM MUNICIPIO M INNER JOIN PARROQUIA P ON M.MUNICIPIO_ID = P.MUNICIPIO_ID
WHERE  UPPER(M.NOMBRE_MUNICIPIO) LIKE '%MARACAIBO%' AND UPPER(P.NOMBRE_PARROQUIA) LIKE 'CHIQUINQUIRA' or UPPER(P.NOMBRE_PARROQUIA) LIKE 'ANTONIO BORJAS ROMERO' GROUP BY M.NOMBRE_MUNICIPIO, P.NOMBRE_PARROQUIA) AS TABLA
WHERE S.PARROQUIA_ID = TABLA.PARROQUIA_ID
group by tabla.nombre_municipio



UPDATE PARROQUIA
SET COLOR_PARROQUIA = 300
WHERE COLOR_PARROQUIA = PARROQUIA_ID



INSERT INTO PARROQUIA (PARROQUIA_ID,MUNICIPIO_ID,NOMBRE_PARROQUIA,COLOR_PARROQUIA,USUARIO_ID) VALUES(15,'CABIMAS001')