-- EJEMPLO DE CROSS TABLE O PRIVATE

SELECT DISTINCT A.HORA_AGENDA,  
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 1 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS LUNES,
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 2 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS MARTES,
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 3 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS MIERCOLES,
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 4 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS JUEVES,
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 5 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS VIERNES,
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 1 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS SABADO,
(SELECT A1.ACTIVIDAD_AGENDA FROM AGENDA A1 WHERE A1.DIA_AGENDA = 1 AND A1.HORA_AGENDA=A.HORA_AGENDA) AS DOMINGO
FROM AGENDA A
ORDER BY A.HORA_AGENDA

-- NOT IN VS NOT EXISTS

SELECT * FROM SECTOR S
WHERE S.PARROQUIA_ID NOT IN
(SELECT P.PARROQUIA_ID FROM PARROQUIA P WHERE P.MUNICIPIO_ID = 5)

SELECT * FROM SECTOR S
WHERE NOT EXISTS
(SELECT 1 FROM PARROQUIA P WHERE P.MUNICIPIO_ID = 5 AND S.PARROQUIA_ID = P.PARROQUIA_ID)

SELECT * FROM
PARROQUIA,SECTOR